[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit ADXL345
    adafruit/Adafruit Unified Sensor
    mikalhart/TinyGPSPlus